export type Icon = 'settings'
  | 'settings-active'
  | 'matches'
  | 'matches-active'
  | 'feed-active'
  | 'feed'
  | 'link'
  | 'approve'
  | 'cancel'
  | 'like'
  | 'dislike'
  | 'points'
  | 'plus-attachment'
  | 'trash'
  | 'arrow-reload'
  | null
